clientid="client_1Q6iX3A1UjKNUZxEeV7P"
#Either add client_secret here, or override by setting the environment variable FOXY_CLIENTSECRET
#clientsecret=
refreshtoken="W2B9upaRrfwQtGP4VPLTR4QLlMdC6btP4Qy9UUGY"
baseurl = "https://api.foxycart.com"